/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        white: '#FFFFFF',
        fogWhite: '#FCFCFC',
        gray: {
          10: '#FAFAFB',
          20: '#f4f4f5',
          30: '#E8E8E9',
          40: '#E0E2E8',
          50: '#BDC1C5',
          60: '#9FA5AD',
          70: '#62686d',
          80: '#454A50',
        },
        black: '#1b1d1f',
        alert: {
          DEFAULT: '#FF4A4A',
          10: '#FFF3F3',
          20: '#FFC1C1',
          30: '#FF9292',
          40: '#FFC1C1',
          50: '#FF5C5C',
        },
        main: '#9F6BFF',
        purple: {
          10: '#F9F5FF',
          20: '#EDE3FF',
          30: '#cfb6ff',
          40: '#bc98ff',
          70: '#8b4dff',
          80: '#4C17AF',
        },
        blue: {
          DEFAULT: '#82A5FF',
          10: '#f4f7ff',
          20: '#E9EBF8',
          30: '#d0ddff',
          40: '#a0baff',
          70: '#4C85FB',
          80: '#001D4A',
        },
        pink: {
          DEFAULT: '#FF83A1',
          10: '#FFF7FB',
          20: '#FFEBF5',
          30: '#FFC3D7',
        },
        secondaryBlue: '#7199FF',
        accentPink: '#FC7B8B',
        hotelYellow: '#FFFCEA',
        kinderGreen: '#F5FEF4',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        heading: ['Poppins', 'sans-serif'],
        pretendard: ['Pretendard', 'sans-serif'],
        jalnan2: ['Jalnan2', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('tailwind-scrollbar-hide'),
    function ({ addUtilities }) {
      const newUtilities = {
        // Title
        '.tLgB22Ls2': {
          fontWeight: '700',
          fontSize: '22px',
          letterSpacing: '-0.44px',
          lineHeight: '1',
        },
        '.tLgB20Ls2': {
          fontWeight: '700',
          fontSize: '20px',
          letterSpacing: '-0.4px',
          lineHeight: '1.2',
        },
        '.tMdB22Ls2': {
          fontWeight: '700',
          fontSize: '22px',
          letterSpacing: '-0.44px',
          lineHeight: '1.2',
        },
        '.tMdB18Ls3': {
          fontWeight: '700',
          fontSize: '18px',
          letterSpacing: '-0.54px',
          lineHeight: '1.2',
        },
        '.tMdB16Ls3': {
          fontWeight: '700',
          fontSize: '16px',
          letterSpacing: '-0.48px',
          lineHeight: '1.2',
        },
        '.tMdSb16Ls3': {
          fontFamily: 'Pretendard, sans-serif',
          fontWeight: '600',
          fontSize: '16px',
          letterSpacing: '-0.48px',
          lineHeight: '1.2',
        },
        '.tLgSb15Ls2': {
          fontWeight: '600',
          fontSize: '15px',
          letterSpacing: '-0.3px',
          lineHeight: '1',
        },
        '.tMSb12Ls2': {
          fontWeight: '600',
          fontSize: '12px',
          letterSpacing: '-0.24px',
          lineHeight: '1.2',
        },
        '.tMM12Ls2': {
          fontWeight: '500',
          fontSize: '12px',
          letterSpacing: '-0.24px',
          lineHeight: '1.2',
        },
        '.tMnSb13Ls2': {
          fontWeight: '600',
          fontSize: '13px',
          letterSpacing: '-0.27px',
          lineHeight: '1.2',
        },
        '.tMnSb135Ls2': {
          fontWeight: '600',
          fontSize: '13.5px',
          letterSpacing: '-0.27px',
          lineHeight: '1.2',
        },
        '.tMnM13Ls2': {
          fontWeight: '500',
          fontSize: '13px',
          letterSpacing: '-0.26px',
          lineHeight: '1.2',
        },
        '.tMnM135Ls2': {
          fontWeight: '500',
          fontSize: '13.5px',
          letterSpacing: '-0.27px',
          lineHeight: '1.2',
        },
        '.tSmB15Ls2': {
          fontWeight: '700',
          fontSize: '15px',
          letterSpacing: '-0.3px',
          lineHeight: '1.2',
        },
        '.tSmM15Ls2': {
          fontWeight: '500',
          fontSize: '15px',
          letterSpacing: '-0.3px',
          lineHeight: '1.2',
        },
        '.tSmM15Ls2Cancel': {
          fontWeight: '500',
          fontSize: '15px',
          letterSpacing: '-0.3px',
          lineHeight: '1.2',
          textDecoration: 'line-through',
        },
        '.tSmM14Ls2': {
          fontWeight: '500',
          fontSize: '14px',
          letterSpacing: '-0.28px',
          lineHeight: '1.2',
        },
        '.tSmSb14Ls2': {
          fontWeight: '600',
          fontSize: '14px',
          letterSpacing: '-0.28px',
          lineHeight: '1.2',
        },
        '.tSmSb15Ls2': {
          fontWeight: '600',
          fontSize: '15px',
          letterSpacing: '-0.3px',
          lineHeight: '1.2',
        },

        // Text
        '.txLgR16Ls3': {
          fontFamily: 'Pretendard, sans-serif',
          fontWeight: '400',
          fontSize: '16px',
          letterSpacing: '-0.32px',
          lineHeight: '1.2',
        },
        '.txLgR16Ls3H15': {
          fontFamily: 'Pretendard, sans-serif',
          fontWeight: '400',
          fontSize: '16px',
          letterSpacing: '-0.32px',
          lineHeight: '1.5',
        },
        '.txLgM16Ls3': {
          fontWeight: '500',
          fontSize: '16px',
          letterSpacing: '-0.48px',
          lineHeight: '1.2',
        },
        '.txMdM16Ls3': {
          fontFamily: 'Pretendard, sans-serif',
          fontWeight: '500',
          fontSize: '16px',
          letterSpacing: '-0.48px',
          lineHeight: '1.2',
        },
        '.txMdM14Ls3': {
          fontWeight: '500',
          fontSize: '14px',
          letterSpacing: '-0.42px',
          lineHeight: '1.2',
        },
        '.txMdM14Ls3H': {
          fontWeight: '500',
          fontSize: '14px',
          letterSpacing: '-0.42px',
          lineHeight: '1.5',
        },
        '.txMdM14Ls3UL': {
          fontWeight: '500',
          fontSize: '14px',
          letterSpacing: '-0.42px',
          lineHeight: '1.4',
          textDecoration: 'underline',
        },
        '.txMdR14Ls3': {
          fontFamily: 'Pretendard, sans-serif',
          fontWeight: '400',
          fontSize: '14px',
          letterSpacing: '-0.45px',
          lineHeight: '1.4',
        },
        '.txMdR15Ls3': {
          fontFamily: 'Pretendard, sans-serif',
          fontWeight: '400',
          fontSize: '15px',
          letterSpacing: '-0.45px',
          lineHeight: '1.4',
        },
        '.txMdR15Ls3UL': {
          fontWeight: '700',
          fontSize: '15px',
          letterSpacing: '-0.45px',
          lineHeight: '1.4',
          textDecoration: 'underline',
        },
        '.txMdR16Ls3': {
          fontWeight: '400',
          fontSize: '14px',
          letterSpacing: '-0.42px',
          lineHeight: '1.4',
        },
        '.txMdiM14Ls2': {
          fontWeight: '500',
          fontSize: '14px',
          letterSpacing: '-0.28px',
          lineHeight: '1.2',
        },
        '.txMdiR14Ls2': {
          fontWeight: '400',
          fontSize: '14px',
          letterSpacing: '-0.28px',
          lineHeight: '1.2',
        },
        '.txMdiR14Ls3': {
          fontWeight: '400',
          fontSize: '14px',
          letterSpacing: '-0.42px',
          lineHeight: '1.2',
        },
        '.txMdiR14Ls2H14': {
          fontWeight: '400',
          fontSize: '14px',
          letterSpacing: '-0.28px',
          lineHeight: '1.4',
        },
        '.txMdSb14Ls3UL': {
          fontWeight: '600',
          fontSize: '14px',
          letterSpacing: '-0.28px',
          lineHeight: '1.2',
          textDecoration: 'underline',
        },
        '.txMdiR14Ls2UL': {
          fontWeight: '400',
          fontSize: '14px',
          letterSpacing: '-0.28px',
          lineHeight: '1.2',
          textDecoration: 'underline',
        },
        '.txMnlM13Ls2': {
          fontWeight: '500',
          fontSize: '13px',
          letterSpacing: '-0.26px',
          lineHeight: '1.2',
        },
        '.txMnlM13Ls2UL': {
          fontWeight: '500',
          fontSize: '13px',
          letterSpacing: '-0.26px',
          lineHeight: '1.2',
          textDecoration: 'underline',
        },
        '.txMnM13Ls2': {
          fontWeight: '500',
          fontSize: '13px',
          letterSpacing: '-0.26px',
          lineHeight: '1.2',
        },
        '.txMnM13H15Ls2': {
          fontWeight: '500',
          fontSize: '13px',
          letterSpacing: '-0.26px',
          lineHeight: '1.5',
        },
        '.txMnR13Ls2': {
          fontWeight: '400',
          fontSize: '13px',
          letterSpacing: '-0.26px',
          lineHeight: '1.2',
        },
        '.txMnR13Ls2UL': {
          fontWeight: '400',
          fontSize: '13px',
          letterSpacing: '-0.26px',
          lineHeight: '1.3',
          textDecoration: 'underline',
        },
        '.txMnR13Ls2Cen': {
          fontWeight: '400',
          fontSize: '13px',
          letterSpacing: '-0.26px',
          lineHeight: '1.2',
        },
        '.txMnM12Ls2': {
          fontWeight: '500',
          fontSize: '12px',
          letterSpacing: '-0.24px',
          lineHeight: '1.2',
        },

        // Caption
        '.cMdSb14Ls2': {
          fontWeight: '600',
          fontSize: '14px',
          letterSpacing: '-0.28px',
          lineHeight: '1.2',
        },
        '.cMdSb14Ls2H14': {
          fontWeight: '600',
          fontSize: '14px',
          letterSpacing: '-0.28px',
          lineHeight: '1.4',
        },
        '.cMdM14Ls2': {
          fontWeight: '500',
          fontSize: '14px',
          letterSpacing: '-0.28px',
          lineHeight: '1.2',
        },
        '.cMdSb12Ls2': {
          fontWeight: '600',
          fontSize: '12px',
          letterSpacing: '-0.24px',
          lineHeight: '1.2',
        },
        '.cSmSb12Ls2': {
          fontFamily: 'Pretendard, sans-serif',
          fontWeight: '600',
          fontSize: '12px',
          letterSpacing: '-0.24px',
          lineHeight: '1.2',
        },
        '.cSmR12Ls2UL': {
          fontWeight: '400',
          fontSize: '12px',
          letterSpacing: '-0.36px',
          lineHeight: '1.2',
          textDecoration: 'underline',
        },
        '.cSmR12Ls2': {
          fontFamily: 'Pretendard, sans-serif',
          fontWeight: '400',
          fontSize: '12px',
          letterSpacing: '-0.24px',
          lineHeight: '1.2',
        },
        '.cSmR20Ls2': {
          fontFamily: 'Pretendard, sans-serif',
          fontWeight: '400',
          fontSize: '20px',
          letterSpacing: '-0.26px',
        },

        // Button
        '.bLgB16Ls1': {
          fontWeight: '700',
          fontSize: '16px',
          letterSpacing: '-0.16px',
          lineHeight: '1.2',
        },
        '.bMdB15Ls2': {
          fontWeight: '700',
          fontSize: '15px',
          letterSpacing: '-0.3px',
          lineHeight: '1.2',
        },
        '.bMdB15Ls2UL': {
          fontWeight: '700',
          fontSize: '15px',
          letterSpacing: '-0.3px',
          lineHeight: '1.2',
          textDecoration: 'underline',
        },
        '.bMdSb14Ls2': {
          fontWeight: '600',
          fontSize: '14px',
          letterSpacing: '-0.28px',
          lineHeight: '1.2',
        },
        '.bMdB13Ls1': {
          fontWeight: '700',
          fontSize: '13px',
          letterSpacing: '-0.13px',
          lineHeight: '1.2',
        },
        '.bMdB13Ls1UL': {
          fontWeight: '700',
          fontSize: '13px',
          letterSpacing: '-0.13px',
          lineHeight: '1.2',
          textDecoration: 'underline',
        },
        '.bMdSb12Ls1': {
          fontWeight: '600',
          fontSize: '12px',
          letterSpacing: '-0.12px',
          lineHeight: '1.2',
        },
        '.tLgEb20Ls3': {
          fontWeight: '800',
          fontSize: '20px',
          letterSpacing: '-0.6px',
          lineHeight: '1',
        },
        '.tLgEb14Ls3': {
          fontWeight: '800',
          fontSize: '14px',
          letterSpacing: '-0.42px',
          lineHeight: '1.2',
        },
        '.tLgSb14Ls3UL': {
          fontWeight: '600',
          fontSize: '14px',
          letterSpacing: '-0.42px',
          lineHeight: '1.2',
          textDecoration: 'underline',
        },
        '.tLgEb16Ls3': {
          fontWeight: '800',
          fontSize: '16px',
          letterSpacing: '-0.48px',
          lineHeight: '1.2',
        },
        '.tLgb16Ls1': {
          fontWeight: '700',
          fontSize: '16px',
          letterSpacing: '-0.13px',
        },
        '.tLgSb10Ls1': {
          fontWeight: '600',
          fontSize: '10px',
          letterSpacing: '-0.1px',
          lineHeight: '1.2',
        },
        '.txMdM10Ls3': {
          fontWeight: '500',
          fontSize: '10px',
          letterSpacing: '-0.3px',
          lineHeight: '1.2',
        },
        '.txMnB11Ls2': {
          fontWeight: '700',
          fontSize: '11px',
          letterSpacing: '-0.22px',
          lineHeight: '1.2',
        },
      };

      addUtilities(newUtilities);
    }
  ],
}